shim-version: v0.3.18@sha256:7d9f98be78c91ede89f43c948a12d084fae34312effe9395ca7ed572991cb561
cvm-version: 0.6.7
cpus: 8
memory: 16384

containers:
  - name: "qwen2-5-05b"
    image: "ghcr.io/tinfoilsh/qwen2-5-05b:v0.0.9"
    env:
      - MODEL_NAME: "Qwen/Qwen2.5-0.5B-Instruct-GGUF"
      - PORT: "8000"
      - CONTEXT_SIZE: "8192"
      - CUDA_VISIBLE_DEVICES: ""

shim:
  listen-port: 443
  upstream-port: 8000
  paths:
    - /v1/chat/completions
    - /health
    - /metrics
