shim-version: v0.3.15@sha256:fbb08eff2b332098751f02c5829531cdcda5a30820370d58cb201a6c6215e59a
cvm-version: 0.5.8
cpus: 4
memory: 4096
gpus: none

containers:
  - name: "qwen2-5-05b"
    image: "ghcr.io/tinfoilsh/qwen2-5-05b:v0.0.7"
    args:
      [
        "-e",
        "MODEL_NAME=Qwen/Qwen2.5-0.5B-Instruct-GGUF",
        "-e",
        "PORT=8000",
        "-e",
        "CONTEXT_SIZE=8192",
        "-e",
        "CUDA_VISIBLE_DEVICES=",
      ]

shim:
  listen-port: 443
  upstream-port: 8000
  publish-attestation: true
  tls-challenge: dns
  paths:
    - /v1/chat/completions
    - /health
    - /metrics
