shim-version: v0.3.16@sha256:20220be4487f241e7e2a9af6dd576d20ba35d71307bd777c8dba9ba5da03fb38
cvm-version: 0.6.7
cpus: 8
memory: 16384

containers:
  - name: "qwen2-5-05b"
    image: "ghcr.io/tinfoilsh/qwen2-5-05b:v0.0.9"
    env:
      - MODEL_NAME: "Qwen/Qwen2.5-0.5B-Instruct-GGUF"
      - PORT: "8000"
      - CONTEXT_SIZE: "8192"
      - CUDA_VISIBLE_DEVICES: ""

shim:
  listen-port: 443
  upstream-port: 8000
  paths:
    - /v1/chat/completions
    - /health
    - /metrics
